### ISSUE TITLE
Cocos3d projects missing files[Huge Problem]

### ISSUE THREAD

**Issue by ronansparks** [cocos3d/cocos3d#16]
After using "./install-cocos3d.sh -2 /Users/Ronan/Library/Cocos2d34". It did generate some new file, But When I run CC3HelloWorld Projects in Cocos3d/Projects, I got error: no such file or directory: 'mypath/cocos2d-chipmunk/chipmunk/src/cpShape.c' and more error like this.  When I go to the chipmunk folder, there's no src folder. What's going on ? 
![screen shot 2015-04-11 at 5 38 56 pm](https://cloud.githubusercontent.com/assets/3815387/7100980/cc3cf848-e071-11e4-8f9f-eec2e9915dfd.png)

**Comment by ronansparks** [comment]
BTW, I'm using lasted version, Cocos2d 3.4 and Cocos3d 2.02.
It seems missing a lot file in Project, after ./install-cocos3d.sh -2 /Users/Ronan/Library/Cocos2d34  command.

**Comment by jpszczerba** [comment]
Read the README.md. Under "Installation" section:
"Note: Cocos3D 2.0 is not compatible with Cocos2D 3.3 and above, as substantial changes to integration design were made in Cocos2D 3.3. Development of Cocos3D 3.0 is underway, which will provide exciting new features, and compatibility with future versions of Cocos2D. Cocos3D 3.0 will not retain compatibility with versions of Cocos2D earlier than Cocos2D 3.3, and will not support OpenGLES 1.1."

Just use older version of Cocos2d (http://cocos2d.spritebuilder.com/download -> "Archive Releases" -> "Cocos2D zip archive 3.2.1") and everything should work.
